name: Testing
on:
  workflow_dispatch:

jobs:
  update-json:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Read input.yml and set params
        id: set-params
        run: |
          for param in $(cat input.yml | awk -F': ' '{print $1}'); do
            value=$(cat input.yml | grep "^$param" | cut -d ':' -f 2 | tr -d ' ')
            echo "::set-output name=$param::$value"
          done

      - name: Update run.json with params
        run: |
          for param in $(cat input.yml | awk -F': ' '{print $1}'); do 
            sed -i "s/{$param}/$(echo ${{ steps.set-params.outputs[$param] }})/g" run.json
          done

      - name: Verify updated content of run.json
        run: cat run.json
