name: Testing

on:
  push:
    branches:
      - template
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
            ref: "refs/heads/template"
 
      - name: Set up Python 
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r Configs/requirements.txt

      - name: Read parameters from input.yml and replace placeholders
        run: |
          python Configs/script.py
          
      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Apply changes"
          git push origin template
