name: Testing
on:
  workflow_dispatch:

jobs:
  update-json:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Read input.yml
        id: read-input
        run: echo "::set-output name=param::$(cat input.yml | cut -d ':' -f 2 | tr -d ' ')"
      
      - name: Update run.json
        run: |
          sed -i "s/{param}/$(echo ${{ steps.read-input.outputs.param }})/g" run.json
          
      - name: Verify testname
        run: |
          cat run.json
