name: Testing

on:
  workflow_dispatch:

jobs:
  update-json:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Read input.yml and set params
        id: set-params
        run: |
          for param in $(cat input.yml | awk -F': ' '{print $1}'); do
            value=$(cat input.yml | grep "^$param" | cut -d ':' -f 2 | tr -d ' ')
            echo "::set-output name=$param::$value"
          done

      - name: Update run.json with params
        run: |
          params=$(echo "${{ steps.set-params.outputs.params }}" | jq -r 'to_entries|map("\(.key)=\(.value|tostring)")|.[]')
          for param in $params; do 
            key=$(echo $param | cut -d'=' -f1)
            value=$(echo $param | cut -d'=' -f2)
            sed -i "s/{$key}/$value/g" run.json
          done

      - name: Verify updated content of run.json
        run: cat run.json
