name: Testing

on:
  workflow_dispatch:

jobs:
  update-json:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Read input.yml and set params
        id: set-params
        run: |
            for param in $(cat input.yml | awk -F': ' '{print $1}'); do
                value=$(cat input.yml | grep "^$param" | cut -d ':' -f 2 | tr -d ' ')
                echo "Extracted Parameter: $param"
                echo "Extracted Value: $value"
                
                # Set output only if value is not empty
                if [ ! -z "$value" ]; then
                    echo "::set-output name=$param::$value"
                fi
            done
